### ISSUE TITLE
Change screenshot without background

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/juriserp-web#12]
Update the screenshot to be without background like previous one.
![image](https://user-images.githubusercontent.com/30463117/174519805-eb01e087-ca8d-4905-a524-40bc94eeebe1.png)

**Comment by russel0907** [comment]
**Change screenshot without background in tab section**
- update to png so other browser can support the image render.
- optimize size of screenshot

## view
![Screenshot 2022-06-20 at 12-05-13 JurisERP - Legal Management System](https://user-images.githubusercontent.com/94702093/174523408-7a5dca0f-8b6a-4ccc-bd17-478ca79a57a8.png)
![Screenshot 2022-06-20 at 12-05-18 JurisERP - Legal Management System](https://user-images.githubusercontent.com/94702093/174523416-e9e95f8a-dd00-4eeb-b17f-2b064b5bb2dc.png)
![Screenshot 2022-06-20 at 12-05-23 JurisERP - Legal Management System](https://user-images.githubusercontent.com/94702093/174523418-bd5430d3-e87a-4fe2-8d5c-0300848361a0.png)
![Screenshot 2022-06-20 at 12-05-27 JurisERP - Legal Management System](https://user-images.githubusercontent.com/94702093/174523421-b6d79f9a-f3f4-4f05-8415-11947d9e1ffc.png)
