### ISSUE TITLE
Update user manual

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/juriserp-web#14]
- [x] update screenshots to make it seem more presentable
- [x] proofread and check for typos, and make necessary changes if needed

https://docs.google.com/document/d/1M7I_EM04v5pCzUIuXMCzXPx8SUX2TaMD3TH81B5LXR8/edit?usp=sharing

**Comment by Suzitaothman** [comment]
https://docs.google.com/document/d/1M7I_EM04v5pCzUIuXMCzXPx8SUX2TaMD3TH81B5LXR8/edit?usp=sharing
