### ISSUE TITLE
Redesign screenshot display

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/juriserp-web#8]
You can follow CLIO https://www.clio.com/ as your reference.
Find suitable photos and screenshot.
![image](https://user-images.githubusercontent.com/30463117/173720450-f95f9376-1bc1-476a-acca-f1cb4838aeb3.png)

**Comment by russel0907** [comment]
Redesign screenshot display;

## About 
![Screenshot 2022-06-16 at 09-54-53 JurisERP - Legal Management System](https://user-images.githubusercontent.com/94702093/173975217-3173521f-153c-4b7e-b2d7-9b7365421255.png)


## Tab Section
![Screenshot 2022-06-16 at 09-55-02 JurisERP - Legal Management System](https://user-images.githubusercontent.com/94702093/173975314-1d9c3cfa-3320-4691-8b87-253c29196aa7.png)

![Screenshot 2022-06-16 at 09-55-06 JurisERP - Legal Management System](https://user-images.githubusercontent.com/94702093/173975245-d9264471-5ee0-480b-b4a9-f93812ed7cb1.png)

![Screenshot 2022-06-16 at 09-55-10 JurisERP - Legal Management System](https://user-images.githubusercontent.com/94702093/173975251-6083d696-4029-42f6-b845-27e6f7a718c6.png)

![Screenshot 2022-06-16 at 09-55-15 JurisERP - Legal Management System](https://user-images.githubusercontent.com/94702093/173975262-34b7f1e7-4d64-482e-b1bf-d934275de154.png)
